export interface Country {
  code: string;
  nameAr: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", nameAr: "أفغانستان", flag: "🇦🇫" },
  { code: "AL", nameAr: "ألبانيا", flag: "🇦🇱" },
  { code: "DZ", nameAr: "الجزائر", flag: "🇩🇿" },
  { code: "AD", nameAr: "أندورا", flag: "🇦🇩" },
  { code: "AO", nameAr: "أنغولا", flag: "🇦🇴" },
  { code: "AG", nameAr: "أنتيغوا وبربودا", flag: "🇦🇬" },
  { code: "AR", nameAr: "الأرجنتين", flag: "🇦🇷" },
  { code: "AM", nameAr: "أرمينيا", flag: "🇦🇲" },
  { code: "AU", nameAr: "أستراليا", flag: "🇦🇺" },
  { code: "AT", nameAr: "النمسا", flag: "🇦🇹" },
  { code: "AZ", nameAr: "أذربيجان", flag: "🇦🇿" },
  { code: "BS", nameAr: "جزر البهاما", flag: "🇧🇸" },
  { code: "BH", nameAr: "البحرين", flag: "🇧🇭" },
  { code: "BD", nameAr: "بنغلاديش", flag: "🇧🇩" },
  { code: "BB", nameAr: "بربادوس", flag: "🇧🇧" },
  { code: "BY", nameAr: "بيلاروسيا", flag: "🇧🇾" },
  { code: "BE", nameAr: "بلجيكا", flag: "🇧🇪" },
  { code: "BZ", nameAr: "بليز", flag: "🇧🇿" },
  { code: "BJ", nameAr: "بنين", flag: "🇧🇯" },
  { code: "BT", nameAr: "بوتان", flag: "🇧🇹" },
  { code: "BO", nameAr: "بوليفيا", flag: "🇧🇴" },
  { code: "BA", nameAr: "البوسنة والهرسك", flag: "🇧🇦" },
  { code: "BW", nameAr: "بوتسوانا", flag: "🇧🇼" },
  { code: "BR", nameAr: "البرازيل", flag: "🇧🇷" },
  { code: "BN", nameAr: "بروناي", flag: "🇧🇳" },
  { code: "BG", nameAr: "بلغاريا", flag: "🇧🇬" },
  { code: "BF", nameAr: "بوركينا فاسو", flag: "🇧🇫" },
  { code: "BI", nameAr: "بوروندي", flag: "🇧🇮" },
  { code: "CV", nameAr: "الرأس الأخضر", flag: "🇨🇻" },
  { code: "KH", nameAr: "كمبوديا", flag: "🇰🇭" },
  { code: "CM", nameAr: "الكاميرون", flag: "🇨🇲" },
  { code: "CA", nameAr: "كندا", flag: "🇨🇦" },
  { code: "CF", nameAr: "جمهورية أفريقيا الوسطى", flag: "🇨🇫" },
  { code: "TD", nameAr: "تشاد", flag: "🇹🇩" },
  { code: "CL", nameAr: "تشيلي", flag: "🇨🇱" },
  { code: "CN", nameAr: "الصين", flag: "🇨🇳" },
  { code: "CO", nameAr: "كولومبيا", flag: "🇨🇴" },
  { code: "KM", nameAr: "جزر القمر", flag: "🇰🇲" },
  { code: "CG", nameAr: "الكونغو", flag: "🇨🇬" },
  { code: "CD", nameAr: "الكونغو الديمقراطية", flag: "🇨🇩" },
  { code: "CR", nameAr: "كوستاريكا", flag: "🇨🇷" },
  { code: "HR", nameAr: "كرواتيا", flag: "🇭🇷" },
  { code: "CU", nameAr: "كوبا", flag: "🇨🇺" },
  { code: "CY", nameAr: "قبرص", flag: "🇨🇾" },
  { code: "CZ", nameAr: "التشيك", flag: "🇨🇿" },
  { code: "DK", nameAr: "الدنمارك", flag: "🇩🇰" },
  { code: "DJ", nameAr: "جيبوتي", flag: "🇩🇯" },
  { code: "DM", nameAr: "دومينيكا", flag: "🇩🇲" },
  { code: "DO", nameAr: "جمهورية الدومينيكان", flag: "🇩🇴" },
  { code: "EC", nameAr: "الإكوادور", flag: "🇪🇨" },
  { code: "EG", nameAr: "مصر", flag: "🇪🇬" },
  { code: "SV", nameAr: "السلفادور", flag: "🇸🇻" },
  { code: "GQ", nameAr: "غينيا الاستوائية", flag: "🇬🇶" },
  { code: "ER", nameAr: "إريتريا", flag: "🇪🇷" },
  { code: "EE", nameAr: "إستونيا", flag: "🇪🇪" },
  { code: "SZ", nameAr: "إسواتيني", flag: "🇸🇿" },
  { code: "ET", nameAr: "إثيوبيا", flag: "🇪🇹" },
  { code: "FJ", nameAr: "فيجي", flag: "🇫🇯" },
  { code: "FI", nameAr: "فنلندا", flag: "🇫🇮" },
  { code: "FR", nameAr: "فرنسا", flag: "🇫🇷" },
  { code: "GA", nameAr: "الغابون", flag: "🇬🇦" },
  { code: "GM", nameAr: "غامبيا", flag: "🇬🇲" },
  { code: "GE", nameAr: "جورجيا", flag: "🇬🇪" },
  { code: "DE", nameAr: "ألمانيا", flag: "🇩🇪" },
  { code: "GH", nameAr: "غانا", flag: "🇬🇭" },
  { code: "GR", nameAr: "اليونان", flag: "🇬🇷" },
  { code: "GD", nameAr: "غرينادا", flag: "🇬🇩" },
  { code: "GT", nameAr: "غواتيمالا", flag: "🇬🇹" },
  { code: "GN", nameAr: "غينيا", flag: "🇬🇳" },
  { code: "GW", nameAr: "غينيا بيساو", flag: "🇬🇼" },
  { code: "GY", nameAr: "غيانا", flag: "🇬🇾" },
  { code: "HT", nameAr: "هايتي", flag: "🇭🇹" },
  { code: "HN", nameAr: "هندوراس", flag: "🇭🇳" },
  { code: "HU", nameAr: "المجر", flag: "🇭🇺" },
  { code: "IS", nameAr: "آيسلندا", flag: "🇮🇸" },
  { code: "IN", nameAr: "الهند", flag: "🇮🇳" },
  { code: "ID", nameAr: "إندونيسيا", flag: "🇮🇩" },
  { code: "IR", nameAr: "إيران", flag: "🇮🇷" },
  { code: "IQ", nameAr: "العراق", flag: "🇮🇶" },
  { code: "IE", nameAr: "أيرلندا", flag: "🇮🇪" },
  { code: "IL", nameAr: "إسرائيل", flag: "🇮🇱" },
  { code: "IT", nameAr: "إيطاليا", flag: "🇮🇹" },
  { code: "JM", nameAr: "جامايكا", flag: "🇯🇲" },
  { code: "JP", nameAr: "اليابان", flag: "🇯🇵" },
  { code: "JO", nameAr: "الأردن", flag: "🇯🇴" },
  { code: "KZ", nameAr: "كازاخستان", flag: "🇰🇿" },
  { code: "KE", nameAr: "كينيا", flag: "🇰🇪" },
  { code: "KI", nameAr: "كيريباتي", flag: "🇰🇮" },
  { code: "KP", nameAr: "كوريا الشمالية", flag: "🇰🇵" },
  { code: "KR", nameAr: "كوريا الجنوبية", flag: "🇰🇷" },
  { code: "KW", nameAr: "الكويت", flag: "🇰🇼" },
  { code: "KG", nameAr: "قيرغيزستان", flag: "🇰🇬" },
  { code: "LA", nameAr: "لاوس", flag: "🇱🇦" },
  { code: "LV", nameAr: "لاتفيا", flag: "🇱🇻" },
  { code: "LB", nameAr: "لبنان", flag: "🇱🇧" },
  { code: "LS", nameAr: "ليسوتو", flag: "🇱🇸" },
  { code: "LR", nameAr: "ليبيريا", flag: "🇱🇷" },
  { code: "LY", nameAr: "ليبيا", flag: "🇱🇾" },
  { code: "LI", nameAr: "ليختنشتاين", flag: "🇱🇮" },
  { code: "LT", nameAr: "ليتوانيا", flag: "🇱🇹" },
  { code: "LU", nameAr: "لوكسمبورغ", flag: "🇱🇺" },
  { code: "MG", nameAr: "مدغشقر", flag: "🇲🇬" },
  { code: "MW", nameAr: "مالاوي", flag: "🇲🇼" },
  { code: "MY", nameAr: "ماليزيا", flag: "🇲🇾" },
  { code: "MV", nameAr: "جزر المالديف", flag: "🇲🇻" },
  { code: "ML", nameAr: "مالي", flag: "🇲🇱" },
  { code: "MT", nameAr: "مالطا", flag: "🇲🇹" },
  { code: "MH", nameAr: "جزر مارشال", flag: "🇲🇭" },
  { code: "MR", nameAr: "موريتانيا", flag: "🇲🇷" },
  { code: "MU", nameAr: "موريشيوس", flag: "🇲🇺" },
  { code: "MX", nameAr: "المكسيك", flag: "🇲🇽" },
  { code: "FM", nameAr: "ميكرونيزيا", flag: "🇫🇲" },
  { code: "MD", nameAr: "مولدوفا", flag: "🇲🇩" },
  { code: "MC", nameAr: "موناكو", flag: "🇲🇨" },
  { code: "MN", nameAr: "منغوليا", flag: "🇲🇳" },
  { code: "ME", nameAr: "الجبل الأسود", flag: "🇲🇪" },
  { code: "MA", nameAr: "المغرب", flag: "🇲🇦" },
  { code: "MZ", nameAr: "موزمبيق", flag: "🇲🇿" },
  { code: "MM", nameAr: "ميانمار", flag: "🇲🇲" },
  { code: "NA", nameAr: "ناميبيا", flag: "🇳🇦" },
  { code: "NR", nameAr: "ناورو", flag: "🇳🇷" },
  { code: "NP", nameAr: "نيبال", flag: "🇳🇵" },
  { code: "NL", nameAr: "هولندا", flag: "🇳🇱" },
  { code: "NZ", nameAr: "نيوزيلندا", flag: "🇳🇿" },
  { code: "NI", nameAr: "نيكاراغوا", flag: "🇳🇮" },
  { code: "NE", nameAr: "النيجر", flag: "🇳🇪" },
  { code: "NG", nameAr: "نيجيريا", flag: "🇳🇬" },
  { code: "MK", nameAr: "مقدونيا الشمالية", flag: "🇲🇰" },
  { code: "NO", nameAr: "النرويج", flag: "🇳🇴" },
  { code: "OM", nameAr: "عُمان", flag: "🇴🇲" },
  { code: "PK", nameAr: "باكستان", flag: "🇵🇰" },
  { code: "PW", nameAr: "بالاو", flag: "🇵🇼" },
  { code: "PS", nameAr: "فلسطين", flag: "🇵🇸" },
  { code: "PA", nameAr: "بنما", flag: "🇵🇦" },
  { code: "PG", nameAr: "بابوا غينيا الجديدة", flag: "🇵🇬" },
  { code: "PY", nameAr: "باراغواي", flag: "🇵🇾" },
  { code: "PE", nameAr: "بيرو", flag: "🇵🇪" },
  { code: "PH", nameAr: "الفلبين", flag: "🇵🇭" },
  { code: "PL", nameAr: "بولندا", flag: "🇵🇱" },
  { code: "PT", nameAr: "البرتغال", flag: "🇵🇹" },
  { code: "QA", nameAr: "قطر", flag: "🇶🇦" },
  { code: "RO", nameAr: "رومانيا", flag: "🇷🇴" },
  { code: "RU", nameAr: "روسيا", flag: "🇷🇺" },
  { code: "RW", nameAr: "رواندا", flag: "🇷🇼" },
  { code: "KN", nameAr: "سانت كيتس ونيفيس", flag: "🇰🇳" },
  { code: "LC", nameAr: "سانت لوسيا", flag: "🇱🇨" },
  { code: "VC", nameAr: "سانت فنسنت والغرينادين", flag: "🇻🇨" },
  { code: "WS", nameAr: "ساموا", flag: "🇼🇸" },
  { code: "SM", nameAr: "سان مارينو", flag: "🇸🇲" },
  { code: "ST", nameAr: "ساو تومي وبرينسيبي", flag: "🇸🇹" },
  { code: "SA", nameAr: "المملكة العربية السعودية", flag: "🇸🇦" },
  { code: "SN", nameAr: "السنغال", flag: "🇸🇳" },
  { code: "RS", nameAr: "صربيا", flag: "🇷🇸" },
  { code: "SC", nameAr: "سيشل", flag: "🇸🇨" },
  { code: "SL", nameAr: "سيراليون", flag: "🇸🇱" },
  { code: "SG", nameAr: "سنغافورة", flag: "🇸🇬" },
  { code: "SK", nameAr: "سلوفاكيا", flag: "🇸🇰" },
  { code: "SI", nameAr: "سلوفينيا", flag: "🇸🇮" },
  { code: "SB", nameAr: "جزر سليمان", flag: "🇸🇧" },
  { code: "SO", nameAr: "الصومال", flag: "🇸🇴" },
  { code: "ZA", nameAr: "جنوب أفريقيا", flag: "🇿🇦" },
  { code: "SS", nameAr: "جنوب السودان", flag: "🇸🇸" },
  { code: "ES", nameAr: "إسبانيا", flag: "🇪🇸" },
  { code: "LK", nameAr: "سريلانكا", flag: "🇱🇰" },
  { code: "SD", nameAr: "السودان", flag: "🇸🇩" },
  { code: "SR", nameAr: "سورينام", flag: "🇸🇷" },
  { code: "SE", nameAr: "السويد", flag: "🇸🇪" },
  { code: "CH", nameAr: "سويسرا", flag: "🇨🇭" },
  { code: "SY", nameAr: "سوريا", flag: "🇸🇾" },
  { code: "TW", nameAr: "تايوان", flag: "🇹🇼" },
  { code: "TJ", nameAr: "طاجيكستان", flag: "🇹🇯" },
  { code: "TZ", nameAr: "تنزانيا", flag: "🇹🇿" },
  { code: "TH", nameAr: "تايلاند", flag: "🇹🇭" },
  { code: "TL", nameAr: "تيمور الشرقية", flag: "🇹🇱" },
  { code: "TG", nameAr: "توغو", flag: "🇹🇬" },
  { code: "TO", nameAr: "تونغا", flag: "🇹🇴" },
  { code: "TT", nameAr: "ترينيداد وتوباغو", flag: "🇹🇹" },
  { code: "TN", nameAr: "تونس", flag: "🇹🇳" },
  { code: "TR", nameAr: "تركيا", flag: "🇹🇷" },
  { code: "TM", nameAr: "تركمانستان", flag: "🇹🇲" },
  { code: "TV", nameAr: "توفالو", flag: "🇹🇻" },
  { code: "UG", nameAr: "أوغندا", flag: "🇺🇬" },
  { code: "UA", nameAr: "أوكرانيا", flag: "🇺🇦" },
  { code: "AE", nameAr: "الإمارات العربية المتحدة", flag: "🇦🇪" },
  { code: "GB", nameAr: "المملكة المتحدة", flag: "🇬🇧" },
  { code: "US", nameAr: "الولايات المتحدة الأمريكية", flag: "🇺🇸" },
  { code: "UY", nameAr: "أوروغواي", flag: "🇺🇾" },
  { code: "UZ", nameAr: "أوزبكستان", flag: "🇺🇿" },
  { code: "VU", nameAr: "فانواتو", flag: "🇻🇺" },
  { code: "VE", nameAr: "فنزويلا", flag: "🇻🇪" },
  { code: "VN", nameAr: "فيتنام", flag: "🇻🇳" },
  { code: "YE", nameAr: "اليمن", flag: "🇾🇪" },
  { code: "ZM", nameAr: "زامبيا", flag: "🇿🇲" },
  { code: "ZW", nameAr: "زيمبابوي", flag: "🇿🇼" },
];

export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}

export function getCountryFlag(code: string | null | undefined): string {
  return getCountry(code)?.flag ?? "";
}
